api/urls.py
from django.urls import path
from api.views.issues import IssueListView, IssueDetailView
from api.views.projects import ProjectListView, ProjectDetailView


urlpatterns = [
    path('issues/', IssueListView.as_view(), name='issues'),
    path('projects/', ProjectListView.as_view(), name='projects'),
    path('issues/<int:pk>/', IssueDetailView.as_view(), name='issue_detail_api'),
    path('projects/<int:pk>/', ProjectDetailView.as_view(), name='project_detail_api'),

]

source/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracker.urls')),
    path('api/', include('api.urls')),
]

tracker/urls.py
from django.urls import path
from tracker.views.index import IndexView
from tracker.views.issues import IssueDetailView, IssueCreateView, IssueUpdateView, IssueDeleteView
from tracker.views.projects import ProjectIndexView, ProjectCreateView, ProjectDetailView, IssueCreateProjectView

urlpatterns = [
    path("", IndexView.as_view(), name='index'),
    path("issue/add", IssueCreateView.as_view(), name='issue_create'),
    path("issue/<int:pk>", IssueDetailView.as_view(), name='issue_detail'),
    path('issue/<int:pk>/update/', IssueUpdateView.as_view(), name='issue_update'),
    path('issue/<int:pk>/delete/', IssueDeleteView.as_view(), name='issue_delete'),
    path('issue/<int:pk>/confirm_delete/', IssueDeleteView.as_view(), name='confirm_delete'),
    path('projects', ProjectIndexView.as_view(), name='project_index'),
    path('project/create/', ProjectCreateView.as_view(), name='project_create'),
    path('project/<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('project/<int:pk>/issue/create/', IssueCreateProjectView.as_view(), name='issue_create_project'),

]

tracker/models/issue.py
from django.db import models
from django.utils import timezone


class Issue(models.Model):
    summary = models.CharField(
        max_length=200,
        null=False,
        blank=False,
        verbose_name='Summary'
    )
    description = models.TextField(
        max_length=3000,
        null=True,
        blank=True,
        verbose_name='Description'
    )
    project = models.ForeignKey(
        to='tracker.Project',
        related_name='issues',
        null=False,
        blank=False,
        on_delete=models.RESTRICT
    )
    status = models.ForeignKey(
        to='tracker.Status',
        related_name='issues',
        null=False,
        blank=False,
        on_delete=models.RESTRICT
    )
    type = models.ManyToManyField(
        to='tracker.Type',
        related_name='issues',
        blank=True
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Time created'
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Time updated'
    )
    is_deleted = models.BooleanField(
        verbose_name='Deleted',
        null=False,
        default=False
    )
    deleted_at = models.DateTimeField(
        verbose_name='Deletion time',
        null=True,
        default=None
    )

    def __str__(self):
        return self.summary

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        self.deleted_at = timezone.now()
        self.save()

    class Meta:
        app_label = 'tracker'

tracker/models/project.py
from django.db import models


class Project(models.Model):
    name = models.CharField(
        max_length=200,
        verbose_name='Name'
    )
    description = models.TextField(
        max_length=3000,
        blank=True,
        verbose_name='Description'
    )
    start_date = models.DateField(
        verbose_name='Start date'
    )
    end_date = models.DateField(
        blank=True,
        null=True,
        verbose_name='End date'
    )

    def __str__(self):
        return self.name

    class Meta:
        app_label = 'tracker'

tracker/models/status.py
from django.db import models


class Status(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name='Status'
    )

    def __str__(self):
        return self.name

    class Meta:
        app_label = 'tracker'

tracker/models/type.py
from django.db import models


class Type(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name='Type'
    )

    def __str__(self):
        return self.name

    class Meta:
        app_label = 'tracker'

tracker/forms.py
from django import forms
from django.core.validators import BaseValidator
from .models import Issue, Type, Status, Project


class CustomMaxValidator(BaseValidator):
    def __init__(self, limit_value=50):
        message = 'Maximum summary length is %(limit_value)s symbols. You entered %(show_value)s symbols'
        super().__init__(limit_value=limit_value, message=message)

    def compare(self, value, limit_value):
        return limit_value < value

    def clean(self, x):
        return len(x)


class CustomMinValidator(BaseValidator):
    def __init__(self, limit_value=2):
        message = 'Minimum summary length is %(limit_value)s symbols. You entered %(show_value)s symbols'
        super().__init__(limit_value=limit_value, message=message)

    def compare(self, value, limit_value):
        return limit_value > value

    def clean(self, x):
        return len(x)


class IssueForm(forms.ModelForm):
    summary = forms.CharField(
        validators=(CustomMaxValidator(), CustomMinValidator()))

    class Meta:
        model = Issue
        fields = ['summary', 'description', 'project', 'status', 'type']
        labels = {
            'summary': 'Summary',
            'description': 'Description',
            'project': 'Project',
            'status': 'Status',
            'type': 'Type'
        }

    project = forms.ModelChoiceField(queryset=Project.objects.all())
    status = forms.ModelChoiceField(queryset=Status.objects.all())
    type = forms.ModelMultipleChoiceField(queryset=Type.objects.all())


class SearchForm(forms.Form):
    search = forms.CharField(max_length=20, required=False, label='Search')


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description', 'start_date', 'end_date']
        labels = {
            'name': 'Name',
            'description': 'Description',
            'start_date': 'Start Date',
            'end_date': 'End Date'
        }
        widgets = {
            'start_date': forms.DateInput(attrs={'type': 'date'}),
            'end_date': forms.DateInput(attrs={'type': 'date'})
        }

api/views/projects.py
from django.http import Http404
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from api.serializers import ProjectSerializer
from tracker.models import Project


class ProjectListView(APIView):
    def get(self, request, *args, **kwargs):
        objects = Project.objects.all()
        serializer = ProjectSerializer(objects, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)


class ProjectDetailView(APIView):
    def get_object(self, pk):
        try:
            return Project.objects.get(pk=pk)
        except Project.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        project = self.get_object(pk)
        serializer = ProjectSerializer(project)
        return Response(serializer.data)

    def put(self, request, pk, format=None):
        project = self.get_object(pk)
        serializer = ProjectSerializer(project, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        project = self.get_object(pk)
        project.delete()
        return Response(f"You just deleted project #{pk}", status=status.HTTP_204_NO_CONTENT)

tracker/views/index.py
from django.db.models import Q
from django.utils.http import urlencode
from django.views.generic import ListView
from tracker.forms import SearchForm
from tracker.models import Issue


class IndexView(ListView):
    template_name = 'index.html'
    model = Issue
    context_object_name = 'issues'
    ordering = ('-created_at',)
    paginate_by = 10
    paginate_orphans = 1

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None

    def get_queryset(self):
        queryset = super().get_queryset().exclude(is_deleted=True)
        if self.search_value:
            query = Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

tracker/views/issues.py
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import DeleteView, UpdateView, CreateView, TemplateView
from tracker.forms import IssueForm
from tracker.models import Issue


class IssueCreateView(CreateView):
    template_name = 'issue_create.html'
    model = Issue
    form_class = IssueForm

    def get_success_url(self):
        return reverse('issue_detail', kwargs={'pk': self.object.pk})


class IssueDetailView(TemplateView):
    template_name = 'issue_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        issue = get_object_or_404(Issue, pk=kwargs['pk'])
        context['issue'] = issue
        if issue.type.exists():
            context['types'] = issue.type.all()
        else:
            context['types'] = []
        return context


class IssueUpdateView(UpdateView):
    template_name = 'issue_update.html'
    form_class = IssueForm
    model = Issue

    def get_success_url(self):
        return reverse('issue_detail', kwargs={'pk': self.object.pk})


class IssueDeleteView(DeleteView):
    template_name = 'issue_delete.html'
    model = Issue
    success_url = reverse_lazy('index')

tracker/views/projects.py
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from tracker.forms import ProjectForm, IssueForm
from tracker.models import Project


class ProjectIndexView(ListView):
    template_name = 'projects.html'
    model = Project
    context_object_name = 'projects'
    queryset = Project.objects.order_by('start_date')


class ProjectDetailView(DetailView):
    template_name = 'project_detail.html'
    model = Project
    context_object_name = 'project'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project = self.object
        issues = project.issues.all()
        context['issues'] = issues
        return context


class ProjectCreateView(CreateView):
    template_name = 'project_create.html'
    form_class = ProjectForm
    model = Project

    def get_success_url(self):
        return reverse('project_detail', kwargs={'pk': self.object.pk})


class IssueCreateProjectView(CreateView):
    template_name = 'issue_create.html'
    form_class = IssueForm

    def get_success_url(self):
        return reverse_lazy('project_detail', kwargs={'pk': self.kwargs['pk']})

    def get_initial(self):
        initial = super().get_initial()
        project = get_object_or_404(Project, pk=self.kwargs['pk'])
        initial['project'] = project
        return initial

    def form_valid(self, form):
        project = get_object_or_404(Project, pk=self.kwargs['pk'])
        issue = form.save(commit=False)
        issue.project = project
        issue.save()
        return super().form_valid(form)

tracker/templates/index.html
{% extends 'partial/base.html' %}
{% block title %}
Home
{% endblock %}
{% block menu %}
{% if is_paginated %}
{% include 'partial/pagination.html' %}
{% endif %}
{% include 'partial/search.html' %}
{% endblock %}
{% block content %}
<h1 style="margin: 1rem">Issue Tracker</h1>

{% for issue in issues %}
    {% include 'partial/issue_list.html' %}
{% empty %}
<h1>Tasks are not found!</h1>
{% endfor %}
{% endblock %}

tracker/templates/issue_create.html
{% extends 'partial/base.html' %}
{% block title %}
Issue Create
{% endblock %}
<h1>New Issue</h1>
{% block content %}
<h1 style="margin: 1rem">Issue Create</h1>
<div class="form">
    <form action="{% url 'issue_create' %}" method="post">
        {% include 'partial/form.html' with button_text='Create' %}
    </form>
</div>
{% endblock %}

tracker/templates/issue_delete.html
{% extends 'partial/base.html' %}
{% block title %}
    Delete Issue
{% endblock %}
{% block content %}
<h1 style="margin: 1rem">Delete entry for {{ issue.summary }}?</h1>
    <div class="row" style="margin-left: 1rem">
        <div class="col-md-12">
            <p>Are you sure you want to delete this issue?</p>
            <form action="{% url 'confirm_delete' issue.pk %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Delete</button>
                <a href="{% url 'index' %}" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}

tracker/templates/issue_detail.html
{% extends 'partial/base.html' %}
{% block title %}
Issue
{% endblock %}
{% block menu %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'issue_update' issue.pk %}">Edit</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'issue_delete' issue.pk %}">Delete</a>
</li>
{% endblock %}
{% block content %}
<h1 style="margin: 1rem">Issue</h1>
<div class="container">
    <p>Title: {{ issue.summary }}</p>
    <p>Description: {{ issue.description }}</p>
    <p>Project: {{ issue.project }}</p>
    <p>Status: {{ issue.status }}</p>
    <p>Type:
        {% if types %}
        {% for type in types %}
        {{ type.name }}{% if not forloop.last %}, {% endif %}
        {% endfor %}
        {% else %}
        None
        {% endif %}
    </p>
    <p>Created at: {{ issue.created_at }}</p>
    <p>Updated at: {{ issue.created_at }}</p>
</div>

{% endblock %}

tracker/templates/issue_update.html
{% extends 'partial/base.html' %}
{% block title %}
Issue Update
{% endblock %}
<h1>Edit Article</h1>
{% block content %}
<h1 style="margin: 1rem">Issue Update</h1>
<div class="form">
    <form action="{% url 'issue_update' issue.pk %}" method="post">
        {% include 'partial/form.html' with button_text='Update' %}
    </form>
</div>
{% endblock %}

tracker/templates/project_create.html
{% extends 'partial/base.html' %}
{% block title %}
Issue Create
{% endblock %}
<h1>New Issue</h1>
{% block content %}
<h1 style="margin: 1rem">Project Create</h1>
<div class="form">
    <form action="{% url 'project_create' %}" method="post">
        {% include 'partial/form.html' with button_text='Create' %}
    </form>
</div>
{% endblock %}

tracker/templates/project_detail.html
{% extends 'partial/base.html' %}
{% block title %}{{ project.name }}{% endblock %}
{% block menu %}{% include 'partial/search.html' %}{% endblock %}
{% block content %}
<h1 style="margin: 1rem">{{ project.name }}</h1>
<div class="card" style="margin-bottom: 1rem">
    <div class="card-body">{{ project.description }}</div>
</div>
{% for issue in issues %}
    {% include 'partial/issue_list.html' %}
{% empty %}
<h3>No issues found for this project.</h3>
{% endfor %}
<a href="{% url 'issue_create_project' project.pk %}" class="btn btn-success">Create New Issue</a>
{% endblock %}

tracker/templates/projects.html
{% extends 'partial/base.html' %}
{% block title %}
Projects
{% endblock %}
{% block menu %}
{% endblock %}
{% block content %}
<h1 style="margin: 1rem">Projects</h1>
{% for project in projects %}
<div class="card" style="margin-bottom: 1rem">
    <div class="card-body">
        <a href="{% url 'project_detail' project.pk %}">{{ project.name }}</a>
    </div>
</div>
{% empty %}
<h1>Projects are not found!</h1>
{% endfor %}
{% endblock %}